#setting configuration for H2 database
spring:
   datasource:
      url: jdbc:h2:~/testdb
      driverClassName: org.h2.Driver
      username: ssa
      password: ssa
      hikari:
         poolName: Shubham-Connection-Pool     
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      hibernate.ddl-auto: update
   h2:
      console:
         enabled: true
         path: /h2-console
         settings:
          web-allow-others: true
   application:
      name: cards
   profiles:
      active: dev
   config:
      import: optional:configserver:http://localhost:8071   
          
#server:
#  port: 8082 

management:
  endpoints:
    web:
      exposure:
        include: "*"  