spring:
   datasource:
      url: jdbc:h2:~/testdb
      driverClassName: org.h2.Driver
      username: ssa
      password: ssa
      hikari:
         poolName: Shubham-Connection-Pool     
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      hibernate.ddl-auto: update
   h2:
      console:
         enabled: true
         path: /h2-console
   security:
      oauth2:
        resource:
          filter-order: 3 
